// Mock data for the application - used when backend is unavailable

export const mockAnimals = [
  {
    id: 1,
    name: "Thor",
    species: "Cachorro",
    race: "SRD",
    gender: "M",
    age: "Adulto",
    size: "Grande",
    image: null,
    description: "Thor é um cachorro muito dócil e brincalhão. Adora passear e brincar com outros cães.",
    available: true,
  },
  {
    id: 2,
    name: "Luna",
    species: "Gato",
    race: "SRD",
    gender: "F",
    age: "Filhote",
    size: "Pequeno",
    image: null,
    description: "Luna é uma gatinha carinhosa que adora colo e brincadeiras.",
    available: true,
  },
  {
    id: 3,
    name: "Bob",
    species: "Cachorro",
    race: "Labrador",
    gender: "M",
    age: "Adulto",
    size: "Grande",
    image: null,
    description: "Bob é um labrador muito amigável e sociável com todos.",
    available: true,
  },
  {
    id: 4,
    name: "Mel",
    species: "Gato",
    race: "Siamês",
    gender: "F",
    age: "Adulto",
    size: "Médio",
    image: null,
    description: "Mel é uma gata muito tranquila e carinhosa.",
    available: true,
  },
  {
    id: 5,
    name: "Rex",
    species: "Cachorro",
    race: "Pastor Alemão",
    gender: "M",
    age: "Idoso",
    size: "Grande",
    image: null,
    description: "Rex é um cachorro muito fiel e protetor. Precisa de um lar com espaço.",
    available: true,
  },
  {
    id: 6,
    name: "Mia",
    species: "Gato",
    race: "SRD",
    gender: "F",
    age: "Filhote",
    size: "Pequeno",
    image: null,
    description: "Mia é uma gatinha muito brincalhona e cheia de energia.",
    available: true,
  },
  {
    id: 7,
    name: "Max",
    species: "Cachorro",
    race: "SRD",
    gender: "M",
    age: "Filhote",
    size: "Médio",
    image: null,
    description: "Max é um filhote cheio de energia, adora correr e brincar.",
    available: true,
  },
  {
    id: 8,
    name: "Nina",
    species: "Cachorro",
    race: "Poodle",
    gender: "F",
    age: "Adulto",
    size: "Pequeno",
    image: null,
    description: "Nina é uma poodle muito dócil, ideal para apartamento.",
    available: true,
  },
  {
    id: 9,
    name: "Simba",
    species: "Gato",
    race: "Persa",
    gender: "M",
    age: "Adulto",
    size: "Médio",
    image: null,
    description: "Simba é um gato persa muito calmo e amoroso.",
    available: true,
  },
  {
    id: 10,
    name: "Pipoca",
    species: "Cachorro",
    race: "SRD",
    gender: "F",
    age: "Filhote",
    size: "Pequeno",
    image: null,
    description: "Pipoca é uma filhote muito esperta e carinhosa.",
    available: true,
  },
  {
    id: 11,
    name: "Frederico",
    species: "Cachorro",
    race: "SRD",
    gender: "M",
    age: "Adulto",
    size: "Médio",
    image: null,
    description: "Frederico é um cão muito leal e companheiro.",
    available: true,
  },
  {
    id: 12,
    name: "Flor",
    species: "Gato",
    race: "SRD",
    gender: "F",
    age: "Adulto",
    size: "Pequeno",
    image: null,
    description: "Flor é uma gatinha muito meiga, adora ficar no sol.",
    available: true,
  },
];

export const mockAdoptions = [
  {
    id: 1,
    animalId: 1,
    adopterName: "João Silva",
    adopterEmail: "joao@email.com",
    adopterPhone: "32999001122",
    status: "pending",
    createdAt: "2024-01-15",
  },
  {
    id: 2,
    animalId: 3,
    adopterName: "Maria Santos",
    adopterEmail: "maria@email.com",
    adopterPhone: "32999003344",
    status: "approved",
    createdAt: "2024-02-20",
  },
];

export const mockSponsorships = [
  {
    id: 1,
    animalId: 2,
    sponsorName: "Carlos Oliveira",
    sponsorEmail: "carlos@email.com",
    sponsorPhone: "32999005566",
    monthlyValue: 50,
    status: "active",
    createdAt: "2024-01-10",
  },
  {
    id: 2,
    animalId: 5,
    sponsorName: "Ana Paula",
    sponsorEmail: "ana@email.com",
    sponsorPhone: "32999007788",
    monthlyValue: 100,
    status: "active",
    createdAt: "2024-03-05",
  },
];

export const mockVolunteers = [
  {
    id: 1,
    name: "Pedro Almeida",
    email: "pedro@email.com",
    phone: "32999009900",
    sector: "Canil",
    availability: 8,
    status: "active",
    createdAt: "2024-01-20",
  },
  {
    id: 2,
    name: "Fernanda Costa",
    email: "fernanda@email.com",
    phone: "32999001100",
    sector: "Gatil",
    availability: 4,
    status: "active",
    createdAt: "2024-02-15",
  },
];

