// Mock data for the application - used when backend is unavailable

export const mockAnimals = [
  {
    id: 1,
    name: "Thor",
    species: "canina",
    race: "SRD",
    gender: "M",
    age: "Adulto",
    size: "grande",
    image: null,
    temperament: "Dócil e brincalhão",
    description: "Thor é um cachorro muito dócil e brincalhão. Adora passear e brincar com outros cães.",
    observation: "Thor foi resgatado das ruas quando ainda era filhote. Desde então, se tornou um cão muito leal e companheiro. Ele adora passear ao ar livre e brincar com outros cães. É castrado e está com todas as vacinas em dia.",
    available: true,
  },
  {
    id: 2,
    name: "Luna",
    species: "felina",
    race: "SRD",
    gender: "F",
    age: "Filhote",
    size: "pequeno",
    image: null,
    temperament: "Carinhosa e brincalhona",
    description: "Luna é uma gatinha carinhosa que adora colo e brincadeiras.",
    observation: "Luna foi encontrada abandonada em uma caixa de papelão com apenas 3 semanas de vida. Hoje ela é uma gatinha cheia de energia que adora brincar com bolinhas e dormir no colo. Está vermifugada e com a primeira dose de vacina.",
    available: true,
  },
  {
    id: 3,
    name: "Bob",
    species: "canina",
    race: "Labrador",
    gender: "M",
    age: "Adulto",
    size: "grande",
    image: null,
    temperament: "Amigável e sociável",
    description: "Bob é um labrador muito amigável e sociável com todos.",
    observation: "Bob viveu seus primeiros anos em um lar amoroso, mas infelizmente sua família precisou se mudar e não pôde levá-lo. É um cão extremamente dócil, ótimo com crianças e outros animais. Castrado e vacinado.",
    available: true,
  },
  {
    id: 4,
    name: "Mel",
    species: "felina",
    race: "Siamês",
    gender: "F",
    age: "Adulto",
    size: "medio",
    image: null,
    temperament: "Tranquila e carinhosa",
    description: "Mel é uma gata muito tranquila e carinhosa.",
    observation: "Mel é uma gata siamesa que foi resgatada de uma situação de maus-tratos. Apesar do passado difícil, é extremamente carinhosa e adora ficar perto das pessoas. É castrada, vacinada e muito saudável.",
    available: true,
  },
  {
    id: 5,
    name: "Rex",
    species: "canina",
    race: "Pastor Alemão",
    gender: "M",
    age: "Idoso",
    size: "grande",
    image: null,
    temperament: "Fiel e protetor",
    description: "Rex é um cachorro muito fiel e protetor. Precisa de um lar com espaço.",
    observation: "Rex é um pastor alemão idoso que precisa de um lar tranquilo para seus últimos anos. É muito obediente, já foi treinado e é extremamente leal. Precisa de acompanhamento veterinário regular por conta da idade. Castrado e vacinado.",
    available: true,
  },
  {
    id: 6,
    name: "Mia",
    species: "felina",
    race: "SRD",
    gender: "F",
    age: "Filhote",
    size: "pequeno",
    image: null,
    temperament: "Brincalhona e curiosa",
    description: "Mia é uma gatinha muito brincalhona e cheia de energia.",
    observation: "Mia nasceu em um abrigo e é uma gatinha extremamente curiosa. Adora explorar cada canto da casa e brincar com qualquer objeto que encontra. É muito sociável e se dá bem com outros gatos. Vermifugada e com primeira vacina.",
    available: true,
  },
  {
    id: 7,
    name: "Max",
    species: "canina",
    race: "SRD",
    gender: "M",
    age: "Filhote",
    size: "medio",
    image: null,
    temperament: "Energético e alegre",
    description: "Max é um filhote cheio de energia, adora correr e brincar.",
    observation: "Max foi resgatado junto com seus irmãos de um terreno baldio. É um filhote muito alegre e cheio de energia. Precisa de um lar com espaço para correr e brincar. Está com as primeiras vacinas em dia e vermifugado.",
    available: true,
  },
  {
    id: 8,
    name: "Nina",
    species: "canina",
    race: "Poodle",
    gender: "F",
    age: "Adulto",
    size: "pequeno",
    image: null,
    temperament: "Dócil e companheira",
    description: "Nina é uma poodle muito dócil, ideal para apartamento.",
    observation: "Nina é uma poodle que foi abandonada por sua antiga família. É uma cadela muito dócil e tranquila, ideal para quem mora em apartamento. Adora ficar no colo e é muito companheira. Castrada e com todas as vacinas em dia.",
    available: true,
  },
  {
    id: 9,
    name: "Simba",
    species: "felina",
    race: "Persa",
    gender: "M",
    age: "Adulto",
    size: "medio",
    image: null,
    temperament: "Calmo e amoroso",
    description: "Simba é um gato persa muito calmo e amoroso.",
    observation: "Simba é um gato persa que viveu em um gatil por 2 anos. É extremamente calmo e amoroso, adora ser escovado e ficar próximo das pessoas. Precisa de escovação regular por conta da pelagem longa. Castrado e vacinado.",
    available: true,
  },
  {
    id: 10,
    name: "Pipoca",
    species: "canina",
    race: "SRD",
    gender: "F",
    age: "Filhote",
    size: "pequeno",
    image: null,
    temperament: "Esperta e carinhosa",
    description: "Pipoca é uma filhote muito esperta e carinhosa.",
    observation: "Pipoca foi encontrada sozinha na rua com apenas 2 meses. É uma filhote muito esperta que aprende rápido. Adora brincar e receber carinho. Vermifugada e com a primeira vacina.",
    available: true,
  },
  {
    id: 11,
    name: "Frederico",
    species: "canina",
    race: "SRD",
    gender: "M",
    age: "Adulto",
    size: "medio",
    image: null,
    temperament: "Leal e companheiro",
    description: "Frederico é um cão muito leal e companheiro.",
    observation: "Frederico viveu em situação de rua durante 3 anos antes de ser resgatado. É um cão muito leal que cria vínculos fortes com seus tutores. Precisa de um pouco de paciência no início, mas depois se torna o melhor amigo. Castrado e vacinado.",
    available: true,
  },
  {
    id: 12,
    name: "Flor",
    species: "felina",
    race: "SRD",
    gender: "F",
    age: "Adulto",
    size: "pequeno",
    image: null,
    temperament: "Meiga e independente",
    description: "Flor é uma gatinha muito meiga, adora ficar no sol.",
    observation: "Flor é uma gata adulta muito tranquila que adora tomar banhos de sol na janela. É independente mas muito carinhosa quando quer. Se dá bem com outros gatos e é ideal para quem busca um companheiro calmo. Castrada e vacinada.",
    available: true,
  },
  {
    id: 13,
    name: "Mingau",
    species: "felina",
    race: "Angorá",
    gender: "M",
    age: "Filhote",
    size: "pequeno",
    image: null,
    temperament: "Agitado e carinhoso",
    description: "Mingau é um gatinho angorá cheio de energia e muito carinhoso.",
    observation: "Mingau foi resgatado de uma colônia de gatos de rua. É um filhote muito agitado que adora escalar móveis e brincar com barbantes. Apesar da energia, é extremamente carinhoso e adora dormir junto ao seu tutor. Vermifugado e com primeira vacina.",
    available: true,
  },
  {
    id: 14,
    name: "Pandora",
    species: "felina",
    race: "SRD",
    gender: "F",
    age: "Idoso",
    size: "medio",
    image: null,
    temperament: "Calma e afetuosa",
    description: "Pandora é uma gata idosa muito tranquila e afetuosa.",
    observation: "Pandora é uma gata idosa que perdeu sua tutora. É extremamente carinhosa e precisa de um lar tranquilo para viver seus últimos anos com conforto. Adora colo e ronrona muito. Castrada, vacinada e precisa de acompanhamento veterinário regular.",
    available: true,
  },
  {
    id: 15,
    name: "Felix",
    species: "felina",
    race: "Maine Coon",
    gender: "M",
    age: "Adulto",
    size: "grande",
    image: null,
    temperament: "Sociável e inteligente",
    description: "Felix é um gato Maine Coon muito sociável e inteligente.",
    observation: "Felix é um gato de grande porte da raça Maine Coon. É muito inteligente e sociável, se dá bem com crianças e outros animais. Adora brincar de buscar objetos e é muito comunicativo. Castrado e com todas as vacinas em dia.",
    available: true,
  },
];

export const mockAdoptions = [
  {
    id: 1,
    animalId: 1,
    adopterName: "João Silva",
    adopterEmail: "joao@email.com",
    adopterPhone: "32999001122",
    status: "pending",
    createdAt: "2024-01-15",
  },
  {
    id: 2,
    animalId: 3,
    adopterName: "Maria Santos",
    adopterEmail: "maria@email.com",
    adopterPhone: "32999003344",
    status: "approved",
    createdAt: "2024-02-20",
  },
];

export const mockSponsorships = [
  {
    id: 1,
    animalId: 2,
    sponsorName: "Carlos Oliveira",
    sponsorEmail: "carlos@email.com",
    sponsorPhone: "32999005566",
    monthlyValue: 50,
    status: "active",
    createdAt: "2024-01-10",
  },
  {
    id: 2,
    animalId: 5,
    sponsorName: "Ana Paula",
    sponsorEmail: "ana@email.com",
    sponsorPhone: "32999007788",
    monthlyValue: 100,
    status: "active",
    createdAt: "2024-03-05",
  },
];

export const mockVolunteers = [
  {
    id: 1,
    name: "Pedro Almeida",
    email: "pedro@email.com",
    phone: "32999009900",
    sector: "Canil",
    availability: 8,
    status: "active",
    createdAt: "2024-01-20",
  },
  {
    id: 2,
    name: "Fernanda Costa",
    email: "fernanda@email.com",
    phone: "32999001100",
    sector: "Gatil",
    availability: 4,
    status: "active",
    createdAt: "2024-02-15",
  },
];
